# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"aa_conc.py",
	"aa_supply.py",
	"aa_supply_enzymes.py",
	"aa_growth_limits.py",
	"biosynthesisProductionDynamics.py",
	"carRegulation.py",
	"cellCycleLength.py",
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	"charging_molecules.py",
	"environmental_shift_fluxes.py",
	"functionalUnits.py",
	"functionalUnitsFC.py",
	"growthAffectingPolymerases.py",
	"growth_trajectory.py",
	"kineticsFluxComparison.py",
	"limitedEnzymeGlutcyslig.py",
	"limitedEnzymeUgd.py",
	"limitedMetabolites.py",
	"massFractionSummary.py",
	"massFractionToUnity.py",
	"massShift.py",
	"mene_limitations.py",
	"new_gene_counts.py",
	# "probProteinExistAndDouble.py",
	"polycistronic_transcription.py",
	"ppgpp_regulation.py",
	"proteinAvgCountVsBurstSize.py",
	"proteinCountVsFoldChange.py",
	"proteinCountsValidation.py",
	"proteinExistVsBurstSize.py",
	"proteinFoldChangeVsRnaDeg.py",
	"proteinFoldChangeVsTranscriptionEvents.py",
	"proteinFoldChangeVsTranslationEff.py",
	"replication.py",
	"ribosome_components.py",
	"ribosome_crowding.py",
	"ribosomeProduction.py",
	"ribosomeUsage.py",
	# "rnaVsProteinPerCell.py",
	"rna_decay_03_high.py",
	"rnap_crowding.py",
	"rRNA_operon_expression.py",
	"rrna_regulation.py",
	# The def5 version labels genes by the cohort-wide def5_CI categories, so it is
	# the one that agrees with the per-gene tables. The original is tier legacy
	# (presence frequency, seed 0 only) -- see the SUBGEN_LEGACY tag.
	# "subgenerationalTranscription.py",
	"subgenerationalTranscription_def5.py",
	"tf_binding.py",
	"timeStep.py",
	"transcriptionEvents.py",
	"transcriptionFrequency.py",
	"transcriptionFrequencyOrdered.py",
	# "transcriptionGenomeCoverage.py",
	"translationFrequency.py",
	"trpRegulation.py",
	"trpSynthaseCapacityVsUsage.py",
	"tyrRegulation.py",
]

TAGS = {
	'ACTIVE': ACTIVE,   # all active analyses in this category
	'CORE': [           # the default list to run in development
		"aa_conc.py",
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"cellCycleLength.py",
		"massFractionSummary.py",
		"massFractionToUnity.py",
		"replication.py",
		"timeStep.py",
		],
	'DIVISION': [
		"cellCycleLength.py",
		],
	'ENVIRONMENT_SHIFT': [
		"aa_supply.py",
		"environmental_shift_fluxes.py",  # TODO(jerry): include this?
		"growth_trajectory.py",
		"massShift.py",
		],
	'GROWTH': [
		"aa_conc.py",
		"aa_supply.py",
		"aa_growth_limits.py",
		"aa_supply_enzymes.py",
		"cellCycleLength.py",
		"charging_molecules.py",
		"growthAffectingPolymerases.py",
		"growth_trajectory.py",
		"massFractionSummary.py",
		"ppgpp_regulation.py",
		],
	'METABOLISM': [
		"aa_conc.py",
		"aa_supply.py",
		"aa_growth_limits.py",
		"aa_supply_enzymes.py",
		"centralCarbonMetabolismCorrelationTimeCourse.py",
		"centralCarbonMetabolismScatter.py",
		"kineticsFluxComparison.py",
		"limitedMetabolites.py",
		],
	'PAPER': [
		"environmental_shift_fluxes.py",
		"functionalUnits.py",
		"functionalUnitsFC.py",
		"limitedEnzymeGlutcyslig.py",
		"limitedEnzymeUgd.py",
		"mene_limitations.py",
		"proteinAvgCountVsBurstSize.py",
		"proteinCountVsFoldChange.py",
		"proteinCountsValidation.py",
		"proteinExistVsBurstSize.py",
		"proteinFoldChangeVsRnaDeg.py",
		"transcriptionFrequencyOrdered.py",
		"trpRegulation.py",
		],
	'RNA_DEGRADATION': [
		"rna_decay_03_high.py",
		],
	'REGULATION': [
		"aa_supply.py",
		"aa_growth_limits.py",
		"aa_supply_enzymes.py",
		"biosynthesisProductionDynamics.py",
		"carRegulation.py",
		"tf_binding.py",
		"trpRegulation.py",
		"trpSynthaseCapacityVsUsage.py",
		"tyrRegulation.py",
		],
	'SUBGENERATIONAL': [
		"proteinAvgCountVsBurstSize.py",
		"proteinCountVsFoldChange.py",
		"proteinExistVsBurstSize.py",
		"proteinFoldChangeVsRnaDeg.py",
		"proteinFoldChangeVsTranscriptionEvents.py",
		"proteinFoldChangeVsTranslationEff.py",
		"subgenerationalTranscription_def5.py",
		"transcriptionEvents.py",
		"transcriptionFrequency.py",
		"transcriptionFrequencyOrdered.py",
		"translationFrequency.py",
		],
	# NOTE: the protein*/transcription* scripts above predate this work and use
	# presence-frequency colouring, not def5 + CI. Several also test presence with
	# `counts.sum(axis=0) > 1` where `> 0` is meant (proteinExistVsBurstSize.py:39,
	# proteinAvgCountVsBurstSize.py:41, proteinCountVsFoldChange.py:41,
	# proteinFoldChangeVsTranslationEff.py:39). Treat their categories as legacy.
	'SUBGEN_LEGACY': [
		"subgenerationalTranscription.py",
		],
	'TRANSLATION': [
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"charging_molecules.py",
		"proteinFoldChangeVsTranslationEff.py",  # TODO(jerry): include this?
		"ribosomeProduction.py",
		"ribosomeUsage.py",
		"translationFrequency.py",  # TODO(jerry): include this?
		],
	'VALIDATION': [
		"proteinCountsValidation.py",
		]
	}
