# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	# "compositionFitting.py",
	# "compositionFittingByGeneration.py",
	"figure4_b_e.py",
	"figure5_a.py",
	# "figure5_c.py",
	"histogramDoublingTime.py",
	"histogramFinalMass.py",
	"histogramGrowthRate.py",
	"initialVsFinalMass.py",
	"kinetics_flux_comparison.py",
	"mass_fraction_instantaneous_growth_rates.py",
	"massFractionSummary.py",
	"metabolismFullFluxes.py",
	"proteinCopyNumberDistribution.py",
	"replication.py",
	"rnaCopyNumberDistribution.py",
	# "transcriptFrequency.py",
	# "transcriptionGenomeCoverage.py",
	# "transcriptionGenomeCoverageSecondHalf.py",
]
