"""
Export v2_with_estimators per-pair kcat estimates as flat-directory TSVs.

Reads `kcat_estimates_v2_with_estimators_summary.csv` produced by
`kcat_estimates_v2_with_estimators.py` and writes three TSV files in the same
format the existing `reconstruction/ecoli/flat/kcat_estimates/*.tsv` files use
(provenance comment header + JsonWriter rows: reaction_id, catalyst_id,
kcat_estimate).  Output files:

	* kcat_estimates_v2_gap.tsv          (from kcat_gap_estimate column)
	* kcat_estimates_v2_smoothed_max.tsv (from kcat_smoothed_max_estimate column)
	* kcat_estimates_v2_drop_top_20.tsv  (from kcat_drop_top_20_estimate column)

After running, drop the TSVs into `reconstruction/ecoli/flat/kcat_estimates/`
to make them available to parca as kcat bound sources.  The placeholder TSVs
checked into that directory will be replaced once you do this.

Usage:
	python models/ecoli/analysis/cohort/kcat_estimates_v2_to_tsv.py \\
		<path/to/kcat_estimates_v2_with_estimators_summary.csv> \\
		[--output_dir <dir>]

If --output_dir is omitted, TSVs are written next to the input CSV.
"""

import argparse
import csv
import datetime
import os
import sys

from reconstruction.spreadsheets import CSV_DIALECT, JsonWriter


ESTIMATOR_COLUMNS = {
	'kcat_estimates_v2_gap.tsv':          'kcat_gap_estimate',
	'kcat_estimates_v2_smoothed_max.tsv': 'kcat_smoothed_max_estimate',
	'kcat_estimates_v2_drop_top_20.tsv':  'kcat_drop_top_20_estimate',
}


def _load_kcat_rows(csv_path):
	"""Yield dict rows for kcat-quantity rows of a v2_with_estimators CSV.

	Skips comment lines starting with '#' (provenance header).
	"""
	with open(csv_path, 'r', newline='', encoding='utf-8') as fh:
		# Strip leading provenance comment lines so DictReader gets the
		# header row first.
		lines = []
		for line in fh:
			if line.startswith('#'):
				continue
			lines.append(line)
		reader = csv.DictReader(lines)
		for row in reader:
			if row.get('quantity') == 'kcat':
				yield row


def _format_value(raw):
	"""Parse a CSV cell into a float, or None when missing/blank."""
	if raw is None:
		return None
	raw = raw.strip()
	if raw == '':
		return None
	try:
		val = float(raw)
	except ValueError:
		return None
	if val != val:  # NaN
		return None
	return val


def export_tsvs(csv_path, output_dir, source_label=None):
	"""Write the three estimator TSVs from a v2_with_estimators summary CSV."""
	rows = list(_load_kcat_rows(csv_path))
	if not rows:
		raise RuntimeError(
			f"No kcat-quantity rows found in {csv_path}.  Confirm the file is "
			f"a kcat_estimates_v2_with_estimators_summary CSV.")
	timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
	source_note = f' (source: {source_label})' if source_label else ''

	for filename, column in ESTIMATOR_COLUMNS.items():
		out_path = os.path.join(output_dir, filename)
		# Filter to rows where this estimator has a valid value.
		valid_rows = []
		for row in rows:
			val = _format_value(row.get(column))
			if val is None or val <= 0:
				continue
			valid_rows.append({
				'reaction_id': row['reaction_id'],
				'catalyst_id': row['catalyst_id'],
				'kcat_estimate': val,
			})
		provenance = (
			f'# Generated by models/ecoli/analysis/cohort/'
			f'kcat_estimates_v2_to_tsv.py from {os.path.basename(csv_path)}'
			f'{source_note} on {timestamp}.'
			f' Column: {column}.'
			f' {len(valid_rows)} reaction-catalyst pairs with finite positive'
			f' estimates (skipped {len(rows) - len(valid_rows)} blank/NaN).\n'
		)
		with open(out_path, 'w', newline='', encoding='utf-8') as fh:
			fh.write(provenance)
			writer = JsonWriter(
				fh, ['reaction_id', 'catalyst_id', 'kcat_estimate'],
				dialect=CSV_DIALECT)
			writer.writeheader()
			for entry in valid_rows:
				writer.writerow(entry)
		print(f'Wrote {out_path} ({len(valid_rows)} rows)')


def main(argv=None):
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		'csv_path',
		help='Path to kcat_estimates_v2_with_estimators_summary[_active].csv')
	parser.add_argument(
		'--output_dir',
		default=None,
		help='Directory to write the three TSV files.  Defaults to the '
			'directory containing csv_path.')
	parser.add_argument(
		'--source_label',
		default=None,
		help='Optional short label (e.g. a cohort run name) recorded in the '
			'TSV provenance header.')
	args = parser.parse_args(argv)

	csv_path = os.path.abspath(args.csv_path)
	if not os.path.isfile(csv_path):
		print(f'Error: input CSV not found: {csv_path}', file=sys.stderr)
		return 1
	output_dir = args.output_dir or os.path.dirname(csv_path)
	if not os.path.isdir(output_dir):
		print(f'Error: output_dir not found: {output_dir}', file=sys.stderr)
		return 1
	export_tsvs(csv_path, output_dir, source_label=args.source_label)
	return 0


if __name__ == '__main__':
	sys.exit(main())
