"""
Export v2_with_estimators per-pair kcat estimates as flat-directory TSVs.

Reads `kcat_estimates_v2_with_estimators_summary.csv` produced by
`kcat_estimates_v2_with_estimators.py` and writes three TSV files in the same
format the existing `reconstruction/ecoli/flat/kcat_estimates/*.tsv` files use
(provenance comment header + JsonWriter rows: reaction_id, catalyst_id,
kcat_estimate).  Output files:

	* kcat_estimates_v2_gap.tsv          (from kcat_gap_estimate column)
	* kcat_estimates_v2_smoothed_max.tsv (from kcat_smoothed_max_estimate column)
	* kcat_estimates_v2_drop_top_20.tsv  (from kcat_drop_top_20_estimate column)

After running, drop the TSVs into `reconstruction/ecoli/flat/kcat_estimates/`
to make them available to parca as kcat bound sources.  The placeholder TSVs
checked into that directory will be replaced once you do this.

Pickle mode (--from_dump): regenerate only the gap TSV at an arbitrary log10
threshold straight from the top-K dump (kcat_estimates_v2_top_k_gap.pkl,
produced when SAVE_TOP_K_GAP_DUMP=True).  The dump keeps the per-pair top-K
samples, so the gap estimate can be recomputed at any threshold without
re-reading the cohort.  Uses the live `_gap_estimate` so it can never drift
from the production estimator.

Usage:
	# CSV mode (all three estimators at their built-in thresholds):
	python models/ecoli/analysis/cohort/kcat_estimates_v2_to_tsv.py \\
		<path/to/kcat_estimates_v2_with_estimators_summary.csv> \\
		[--output_dir <dir>]

	# Pickle mode (gap estimator only, at a chosen threshold):
	python models/ecoli/analysis/cohort/kcat_estimates_v2_to_tsv.py \\
		--from_dump <path/to/kcat_estimates_v2_top_k_gap.pkl> \\
		--threshold 0.3 [--output_dir <dir>]

If --output_dir is omitted, TSVs are written next to the input file.
"""

import argparse
import csv
import datetime
import os
import sys

from reconstruction.spreadsheets import CSV_DIALECT, JsonWriter


ESTIMATOR_COLUMNS = {
	'kcat_estimates_v2_gap.tsv':          'kcat_gap_estimate',
	'kcat_estimates_v2_smoothed_max.tsv': 'kcat_smoothed_max_estimate',
	'kcat_estimates_v2_drop_top_20.tsv':  'kcat_drop_top_20_estimate',
}


def _load_kcat_rows(csv_path):
	"""Yield dict rows for kcat-quantity rows of a v2_with_estimators CSV.

	Skips comment lines starting with '#' (provenance header).
	"""
	with open(csv_path, 'r', newline='', encoding='utf-8') as fh:
		# Strip leading provenance comment lines so DictReader gets the
		# header row first.
		lines = []
		for line in fh:
			if line.startswith('#'):
				continue
			lines.append(line)
		reader = csv.DictReader(lines)
		for row in reader:
			if row.get('quantity') == 'kcat':
				yield row


def _format_value(raw):
	"""Parse a CSV cell into a float, or None when missing/blank."""
	if raw is None:
		return None
	raw = raw.strip()
	if raw == '':
		return None
	try:
		val = float(raw)
	except ValueError:
		return None
	if val != val:  # NaN
		return None
	return val


def export_tsvs(csv_path, output_dir, source_label=None):
	"""Write the three estimator TSVs from a v2_with_estimators summary CSV."""
	rows = list(_load_kcat_rows(csv_path))
	if not rows:
		raise RuntimeError(
			f"No kcat-quantity rows found in {csv_path}.  Confirm the file is "
			f"a kcat_estimates_v2_with_estimators_summary CSV.")
	timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
	source_note = f' (source: {source_label})' if source_label else ''

	for filename, column in ESTIMATOR_COLUMNS.items():
		out_path = os.path.join(output_dir, filename)
		# Filter to rows where this estimator has a valid value.
		valid_rows = []
		for row in rows:
			val = _format_value(row.get(column))
			if val is None or val <= 0:
				continue
			valid_rows.append({
				'reaction_id': row['reaction_id'],
				'catalyst_id': row['catalyst_id'],
				'kcat_estimate': val,
			})
		provenance = (
			f'# Generated by models/ecoli/analysis/cohort/'
			f'kcat_estimates_v2_to_tsv.py from {os.path.basename(csv_path)}'
			f'{source_note} on {timestamp}.'
			f' Column: {column}.'
			f' {len(valid_rows)} reaction-catalyst pairs with finite positive'
			f' estimates (skipped {len(rows) - len(valid_rows)} blank/NaN).\n'
		)
		with open(out_path, 'w', newline='', encoding='utf-8') as fh:
			fh.write(provenance)
			writer = JsonWriter(
				fh, ['reaction_id', 'catalyst_id', 'kcat_estimate'],
				dialect=CSV_DIALECT)
			writer.writeheader()
			for entry in valid_rows:
				writer.writerow(entry)
		print(f'Wrote {out_path} ({len(valid_rows)} rows)')


# Pickle mode regenerates only this file -- the top-K dump supports the gap
# estimator alone (smoothed_max / drop_top_20 need the full per-cell pipeline).
GAP_TSV_FILENAME = 'kcat_estimates_v2_gap.tsv'


def export_gap_tsv_from_dump(dump_path, output_dir, threshold,
		source_label=None):
	"""Write the v2_gap TSV from a top-K gap pickle at an arbitrary threshold.

	The pickle (`kcat_estimates_v2_top_k_gap.pkl`, produced by
	kcat_estimates_v2_with_estimators.py with SAVE_TOP_K_GAP_DUMP=True) holds
	the per-pair top-K kcat samples, so the gap estimate can be recomputed at
	any log10 `threshold` without re-reading the cohort.  Reuses the live
	`_gap_estimate` so the emitted TSV can never drift from the production
	estimator.
	"""
	import pickle

	import numpy as np

	# Local import: the estimators module pulls in matplotlib/scipy, so keep it
	# out of the lightweight CSV path.
	from models.ecoli.analysis.cohort.kcat_estimates_v2_with_estimators import (
		_gap_estimate)

	with open(dump_path, 'rb') as fh:
		dump = pickle.load(fh)

	pair_ids = dump['pair_ids']
	valid_rows = []
	for p, (reaction_id, catalyst_id) in enumerate(pair_ids):
		top_k = np.asarray(dump['top_k_gap'][p], dtype=float)
		est = _gap_estimate(
			top_k,
			int(dump['n_samples'][p]),
			float(dump['max'][p]),
			p99_floor=float(dump['p99'][p]),
			threshold_log10=threshold)
		if est is None or not np.isfinite(est) or est <= 0:
			continue
		valid_rows.append({
			'reaction_id': reaction_id,
			'catalyst_id': catalyst_id,
			'kcat_estimate': float(est),
		})

	timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
	source_note = f' (source: {source_label})' if source_label else ''
	out_path = os.path.join(output_dir, GAP_TSV_FILENAME)
	provenance = (
		f'# Generated by models/ecoli/analysis/cohort/'
		f'kcat_estimates_v2_to_tsv.py from {os.path.basename(dump_path)}'
		f'{source_note} on {timestamp}.'
		f' Top-K gap estimator at log10 threshold {threshold:g}.'
		f' {len(valid_rows)} reaction-catalyst pairs with finite positive'
		f' estimates (skipped {len(pair_ids) - len(valid_rows)} non-finite/'
		f'non-positive).\n'
	)
	with open(out_path, 'w', newline='', encoding='utf-8') as fh:
		fh.write(provenance)
		writer = JsonWriter(
			fh, ['reaction_id', 'catalyst_id', 'kcat_estimate'],
			dialect=CSV_DIALECT)
		writer.writeheader()
		for entry in valid_rows:
			writer.writerow(entry)
	print(f'Wrote {out_path} ({len(valid_rows)} rows, gap threshold '
		f'log10={threshold:g})')


def main(argv=None):
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		'csv_path',
		nargs='?',
		default=None,
		help='Path to kcat_estimates_v2_with_estimators_summary[_active].csv '
			'(CSV mode).  Omit when using --from_dump.')
	parser.add_argument(
		'--output_dir',
		default=None,
		help='Directory to write the three TSV files.  Defaults to the '
			'directory containing csv_path.')
	parser.add_argument(
		'--source_label',
		default=None,
		help='Optional short label (e.g. a cohort run name) recorded in the '
			'TSV provenance header.')
	parser.add_argument(
		'--from_dump',
		default=None,
		help='Path to kcat_estimates_v2_top_k_gap.pkl.  When given, regenerate '
			'only the v2_gap TSV from the pickle at --threshold instead of '
			'reading a summary CSV.')
	parser.add_argument(
		'--threshold',
		type=float,
		default=None,
		help='Log10 gap threshold for --from_dump mode (e.g. 0.3 for a ~2x '
			'jump).  Required with --from_dump.')
	args = parser.parse_args(argv)

	if args.from_dump:
		if args.threshold is None:
			print('Error: --threshold is required with --from_dump.',
				file=sys.stderr)
			return 1
		dump_path = os.path.abspath(args.from_dump)
		if not os.path.isfile(dump_path):
			print(f'Error: dump file not found: {dump_path}', file=sys.stderr)
			return 1
		output_dir = args.output_dir or os.path.dirname(dump_path)
		if not os.path.isdir(output_dir):
			print(f'Error: output_dir not found: {output_dir}', file=sys.stderr)
			return 1
		export_gap_tsv_from_dump(dump_path, output_dir, args.threshold,
			source_label=args.source_label)
		return 0

	if not args.csv_path:
		print('Error: provide csv_path (CSV mode) or --from_dump (pickle '
			'mode).', file=sys.stderr)
		return 1
	csv_path = os.path.abspath(args.csv_path)
	if not os.path.isfile(csv_path):
		print(f'Error: input CSV not found: {csv_path}', file=sys.stderr)
		return 1
	output_dir = args.output_dir or os.path.dirname(csv_path)
	if not os.path.isdir(output_dir):
		print(f'Error: output_dir not found: {output_dir}', file=sys.stderr)
		return 1
	export_tsvs(csv_path, output_dir, source_label=args.source_label)
	return 0


if __name__ == '__main__':
	sys.exit(main())
