"""
Sweep gap thresholds against a saved top-K dump produced by
kcat_estimates_v2_with_estimators.py (SAVE_TOP_K_GAP_DUMP=True).

For each (reaction, catalyst) pair, recompute `_gap_estimate` at every
candidate log10 threshold and emit a comparison CSV.  Useful for asking
"what would happen if we lowered GAP_THRESHOLD_LOG10 from 0.5 to 0.3?"
without rerunning the expensive cohort analysis.

Usage:
	python models/ecoli/analysis/cohort/kcat_v2_gap_threshold_compare.py \\
	    <path/to/kcat_estimates_v2_top_k_gap.pkl> \\
	    [--thresholds 0.3 0.4 0.5] \\
	    [--output_csv <path>] \\
	    [--baseline_threshold 0.5]

Output columns: reaction_id, catalyst_id, n_samples, max, p99,
                gap_t{th} for each th, max_over_gap_t{th} for each th,
                newly_trimmed_at_t{th} flag (Y if this threshold trims but
                the baseline did not).

Print summary: how many pairs trim at each threshold and how many newly
trim relative to the baseline.
"""

import argparse
import csv
import os
import pickle
import sys

import numpy as np

# Import the live estimator + its safeguards so the comparison uses the same
# logic the production code uses (no risk of drift).
from models.ecoli.analysis.cohort.kcat_estimates_v2_with_estimators import (
	_gap_estimate,
	GAP_THRESHOLD_LOG10,
)


def _trims(estimate, max_val):
	"""True if `estimate` represents a genuine trim relative to max."""
	if estimate is None or not np.isfinite(estimate):
		return False
	if not np.isfinite(max_val):
		return False
	# A "trim" is anything below max_val by more than a tiny epsilon
	# (the function returns float(max_val) when it declines to trim).
	return (max_val - estimate) > max(1e-9, 1e-9 * abs(max_val))


def main(argv=None):
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument('dump_path',
		help='Path to kcat_estimates_v2_top_k_gap.pkl')
	parser.add_argument('--thresholds', nargs='+', type=float,
		default=[0.2, 0.3, 0.4, 0.5],
		help='Log10 thresholds to evaluate.  Default 0.2 0.3 0.4 0.5.')
	parser.add_argument('--baseline_threshold', type=float,
		default=GAP_THRESHOLD_LOG10,
		help=f'Threshold to compare new thresholds against for the '
			f'"newly trimmed" flag (default {GAP_THRESHOLD_LOG10}).')
	parser.add_argument('--output_csv', default=None,
		help='Output CSV path.  Defaults to alongside dump_path.')
	args = parser.parse_args(argv)

	dump_path = os.path.abspath(args.dump_path)
	if not os.path.isfile(dump_path):
		print(f'Error: dump file not found: {dump_path}', file=sys.stderr)
		return 1
	with open(dump_path, 'rb') as fh:
		d = pickle.load(fh)

	pair_ids = d['pair_ids']
	n_pairs = len(pair_ids)
	thresholds = sorted(set(args.thresholds))
	baseline_t = args.baseline_threshold

	output_csv = (args.output_csv
		or os.path.join(os.path.dirname(dump_path),
			'kcat_v2_gap_threshold_comparison.csv'))

	# Per-pair recomputation across thresholds.
	rows = []
	trim_count = {t: 0 for t in thresholds}
	baseline_estimates = []
	for p in range(n_pairs):
		rxn, cat = pair_ids[p]
		n = int(d['n_samples'][p])
		mx = float(d['max'][p])
		p99 = float(d['p99'][p])
		top_k = np.asarray(d['top_k_gap'][p], dtype=float)

		baseline_est = _gap_estimate(top_k, n, mx,
			p99_floor=p99, threshold_log10=baseline_t)
		baseline_estimates.append(baseline_est)

		gaps_at = {}
		for t in thresholds:
			est = _gap_estimate(top_k, n, mx,
				p99_floor=p99, threshold_log10=t)
			gaps_at[t] = est
			if _trims(est, mx):
				trim_count[t] += 1
		rows.append((rxn, cat, n, mx, p99, baseline_est, gaps_at))

	# Print summary.
	print(f'{n_pairs} pairs evaluated against thresholds '
		f'{thresholds}.  Baseline threshold: {baseline_t}.')
	baseline_trim_count = sum(
		1 for p in range(n_pairs)
		if _trims(baseline_estimates[p], float(d['max'][p])))
	print(f'  baseline (t={baseline_t}): {baseline_trim_count} '
		f'pairs trim ({baseline_trim_count / n_pairs:.0%})')
	for t in thresholds:
		newly = sum(
			1 for p in range(n_pairs)
			if _trims(rows[p][6][t], rows[p][3])
			and not _trims(baseline_estimates[p], rows[p][3]))
		print(f'  t={t:.2f}: {trim_count[t]} trim total '
			f'({trim_count[t] / n_pairs:.0%})'
			f' -- {newly} newly trimmed vs baseline')

	# Write the comparison CSV, sorted by max/gap_at_lowest descending so the
	# pairs most affected by the most-aggressive threshold come first.
	lowest_t = thresholds[0]
	def _sort_key(row):
		_rxn, _cat, _n, mx, _p99, _base, gaps = row
		est = gaps[lowest_t]
		if est is None or not np.isfinite(est) or est <= 0:
			return -np.inf
		return mx / est

	rows.sort(key=_sort_key, reverse=True)

	with open(output_csv, 'w', newline='', encoding='utf-8') as fh:
		fh.write(f'# Generated by kcat_v2_gap_threshold_compare.py from '
			f'{os.path.basename(dump_path)}.  '
			f'Baseline threshold log10 = {baseline_t}.  '
			f'Candidate thresholds = {thresholds}.\n')
		fh.write(f'# A "Y" in newly_trimmed_at_t{{th}} means this pair did '
			f'not trim at the baseline threshold but does at this lower '
			f'threshold.\n')
		fh.write(f'# Sort order: max / gap_t{lowest_t:.2f} descending.\n')
		writer = csv.writer(fh)
		header = [
			'reaction_id', 'catalyst_id', 'n_samples', 'max', 'p99',
			f'baseline_gap_t{baseline_t:.2f}',
		]
		for t in thresholds:
			header.append(f'gap_t{t:.2f}')
		for t in thresholds:
			header.append(f'max_over_gap_t{t:.2f}')
		for t in thresholds:
			header.append(f'newly_trimmed_at_t{t:.2f}')
		writer.writerow(header)

		def _fmt(x):
			if x is None or not np.isfinite(x):
				return ''
			return f'{x:.6g}'

		for rxn, cat, n, mx, p99, base_est, gaps in rows:
			base_trims = _trims(base_est, mx)
			row = [rxn, cat, n, _fmt(mx), _fmt(p99), _fmt(base_est)]
			for t in thresholds:
				row.append(_fmt(gaps[t]))
			for t in thresholds:
				est = gaps[t]
				if est is None or not np.isfinite(est) or est <= 0:
					row.append('')
				else:
					row.append(_fmt(mx / est))
			for t in thresholds:
				cur_trims = _trims(gaps[t], mx)
				row.append('Y' if (cur_trims and not base_trims) else '')
			writer.writerow(row)

	print(f'Wrote {output_csv}')
	return 0


if __name__ == '__main__':
	sys.exit(main())
