#! /usr/bin/env bash
# Run make compile and check requirements to maintain proper environment for wcm

# Only if new branch is check out
if [ $3 -eq 1 ]; then
    "$(git rev-parse --git-path hooks)/wcm-env-check.sh"
fi
